name: garbage_collection_system
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.8
  http: ^0.13.5
  image_picker: ^0.8.5+3
  location: ^4.4.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
